#include "Import.h"
std::vector<std::string> Import::importCode() {
    std::vector<std::string> code;

    // Imports required for the MightyMacro
    code = {
            "/*",
            " * STAR CCM+ macro generated by MightyMacroMaker",
            " */",
            "",
            "// This macro class belongs to macro package",
            "package macro;",
            "",
            "// Java facilities",
            "import java.util.*;",
            "",
            "// STAR-CCM+ specific",
            "import star.common.*;",
            "import star.base.neo.*;",
            "import star.vis.*;",
            "import star.meshing.*;",
            "",
            "// Mesh models",
            "import star.resurfacer.*;",
            "import star.dualmesher.*;",
            "import star.prismmesher.*;",
            "import star.surfacewrapper.*;"
                    "",
            "// Physics",
            "import star.turbulence.*;",
            "import star.kwturb.*;",
            "import star.material.*;",
            "import star.flow.*;",
            "import star.coupledflow.*;",
            "import star.metrics.*;",
            "import star.energy.*;",
            "",
            "// Material Properties",
            "import star.material.*;",
            "",
            "// Reports",
            "import star.base.report.*;",
            ""
    };
    return code;
}