#include "Import.h"

Import::Import(const PrismLayer& _prismLayer, double _dynamicViscosity) :
        prismLayer      (_prismLayer),
        dynamicViscosity(_dynamicViscosity) {}

std::vector<std::string> Import::importCode() {
    std::vector<std::string> code;
    std::vector<std::string> codeBuffer;

    // Imports required for the MightyMacro
    code = {
            "/*",
            " * STAR CCM+ macro generated by MightyMacroMaker",
            " * ",
            " * Author: Nuno Alves de Sousa",
            " */",
            "",
            "// This macro class belongs to macro package",
            "package macro;",
            "",
            "// Java facilities",
            "import java.util.*;",
            "",
            "// STAR-CCM+ specific",
            "import star.common.*;",
            "import star.base.neo.*;",
            "import star.vis.*;",
            "",
            "// Mesh models",
            "import star.meshing.*;",
            "import star.resurfacer.*;",
            "import star.dualmesher.*;",
            "import star.surfacewrapper.*;"
    };

    // Prism mesher
    if(prismLayer.numPrismLayers > 0)
        code.emplace_back("import star.prismmesher.*;");

    // Physics (Inviscid)
    codeBuffer = {
            "",
            "// Physics",
            "import star.material.*;",
            "import star.flow.*;",
            "import star.coupledflow.*;",
            "import star.energy.*;",
            "import star.metrics.*;",
    };
    code.insert(code.end(), codeBuffer.begin(), codeBuffer.end());

    // Extra options for RANS
    if(dynamicViscosity > 0){
        codeBuffer = {
                "import star.turbulence.*;",
                "import star.kwturb.*;",
        };
        code.insert(code.end(), codeBuffer.begin(), codeBuffer.end());
    }

    // Reports
    codeBuffer = {
            "",
            "// Reports",
            "import star.base.report.*;",
    };
    code.insert(code.end(), codeBuffer.begin(), codeBuffer.end());

    return code;
}